# 总体信息
title: "张佳明"
description: > # this means to ignore newlines until "baseurl:"
 张佳明 英文名:smallming 江湖人称:佳明哥 主攻:Java 、 区块链 、 人工智能 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.smallming.com"
permalink: :title/
full-url: "http://www.smallming.com" # the base hostname & protocol for your site


# CSS
sass:
  style: compressed

# Comments - Go to Disqus.com > sign up > get the short-name > insert it here
disqus-shortname: smallming.com

# Tracker
analytics: UA-83979019-1

# Form Settings
#
# Contact form can be enabled by getting an API key from https://getsimpleform.com/
simpleform-token: b6d4be9b039b666b3311e1ddcbfb577c

# Redirect users after submitting the form
redirect-to: http://www.smallming.com

# Site version
version: 1.0


# 日期背景色,默认绿色

change-date-bg: no


# Build settings
markdown: kramdown

include: [_pages] # Includes files inside _pages directory [Do not remove this]

author:
  name: 张佳明
  image: zjm.jpg # The author image will be shown on the header. Place this image in /images/ folder.
  about: /_pages/about.md 
  twitter: no  # https://twitter.com/ is automatically added
  facebook: no # https://facebook.com/ is automatically added
  email: no # mailto: is automatically added
  
gems: 
  - jekyll-seo-tag
  - jekyll-paginate